"""
Node 9: Template Engine

Applies document templates and structure.
"""

from pathlib import Path
from typing import Any, Dict, Optional
from datetime import datetime

from loguru import logger
from jinja2 import Environment, FileSystemLoader, select_autoescape

from .base import BaseNode
from ..core.state import AgentState


class TemplateEngineNode(BaseNode):
    """
    Applies templates to document drafts.
    
    Features:
    - Jinja2 templating
    - Multiple template types
    - Custom template support
    """
    
    node_name = "template_engine"
    max_retries = 2
    
    def __init__(self, config=None):
        super().__init__(config)
        self._env = None
    
    @property
    def env(self) -> Environment:
        """Get Jinja2 environment."""
        if self._env is None:
            template_dir = Path(self.config.documents.templates_dir)
            template_dir.mkdir(parents=True, exist_ok=True)
            
            # Create default templates if they don't exist
            self._create_default_templates(template_dir)
            
            self._env = Environment(
                loader=FileSystemLoader(str(template_dir)),
                autoescape=select_autoescape(["html", "xml"]),
            )
        return self._env
    
    def _create_default_templates(self, template_dir: Path):
        """Create default document templates."""
        # Research report template
        report_template = template_dir / "report.md.j2"
        if not report_template.exists():
            report_template.write_text("""# {{ title }}

**Generated:** {{ metadata.created_at }}
**Query:** {{ query }}

---

{% for section in sections %}
## {{ section.heading }}

{{ section.content }}

{% endfor %}

---

## References

{% for citation in citations %}
- {{ citation }}
{% endfor %}

---

*Document generated by Agent Researcher*
""")
        
        # Brief template
        brief_template = template_dir / "brief.md.j2"
        if not brief_template.exists():
            brief_template.write_text("""# {{ title }}

{{ metadata.created_at }}

{% for section in sections %}
### {{ section.heading }}
{{ section.content }}

{% endfor %}
""")
        
        # HTML template
        html_template = template_dir / "report.html.j2"
        if not html_template.exists():
            html_template.write_text("""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <style>
        body { font-family: Georgia, serif; max-width: 800px; margin: 0 auto; padding: 20px; }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; }
        h2 { color: #34495e; }
        .meta { color: #7f8c8d; font-size: 0.9em; }
        .section { margin: 2em 0; }
        .references { background: #f9f9f9; padding: 1em; border-radius: 5px; }
    </style>
</head>
<body>
    <h1>{{ title }}</h1>
    <p class="meta">Generated: {{ metadata.created_at }}<br>Query: {{ query }}</p>
    
    {% for section in sections %}
    <div class="section">
        <h2>{{ section.heading }}</h2>
        <div>{{ section.content | replace('\n', '<br>') }}</div>
    </div>
    {% endfor %}
    
    <div class="references">
        <h2>References</h2>
        <ul>
        {% for citation in citations %}
            <li>{{ citation }}</li>
        {% endfor %}
        </ul>
    </div>
</body>
</html>
""")
    
    def validate_input(self, state: AgentState) -> tuple[bool, str]:
        """Check for document draft."""
        if not state.get("document_draft"):
            return False, "No document draft to format"
        return True, ""
    
    def process(self, state: AgentState) -> AgentState:
        """Apply template to document draft."""
        draft = state["document_draft"]
        output_format = state.get("output_format", "markdown")
        
        logger.info(f"Applying template for format: {output_format}")
        
        # Select template
        template_name = self._select_template(output_format)
        
        try:
            template = self.env.get_template(template_name)
            
            # Render template
            rendered = template.render(
                title=draft.get("title", "Research Document"),
                query=draft.get("query", ""),
                sections=draft.get("sections", []),
                citations=draft.get("citations", []),
                metadata=draft.get("metadata", {}),
            )
            
            # Store formatted document
            state["formatted_document"] = {
                "content": rendered,
                "format": output_format,
                "template": template_name,
                "rendered_at": datetime.now().isoformat(),
            }
            
            logger.info(f"Template applied successfully: {template_name}")
            
        except Exception as e:
            logger.error(f"Template rendering failed: {e}")
            # Fallback to plain text
            state["formatted_document"] = {
                "content": self._fallback_render(draft),
                "format": "markdown",
                "template": "fallback",
                "rendered_at": datetime.now().isoformat(),
            }
        
        return state
    
    def _select_template(self, output_format: str) -> str:
        """Select appropriate template for format."""
        template_map = {
            "markdown": "report.md.j2",
            "md": "report.md.j2",
            "html": "report.html.j2",
            "brief": "brief.md.j2",
        }
        return template_map.get(output_format, "report.md.j2")
    
    def _fallback_render(self, draft: Dict[str, Any]) -> str:
        """Fallback rendering without templates."""
        parts = [f"# {draft.get('title', 'Document')}\n"]
        
        for section in draft.get("sections", []):
            parts.append(f"\n## {section.get('heading', 'Section')}\n")
            parts.append(section.get("content", ""))
        
        if draft.get("citations"):
            parts.append("\n## References\n")
            for cite in draft["citations"]:
                parts.append(f"- {cite}")
        
        return "\n".join(parts)
